### ISSUE TITLE
Orca Slicer compatible print image

### ISSUE THREAD

**Issue by insp1re1** [QIDITECH/QIDI_SMART3#10]
Allow compatible printer preview images to be displayed when using orca, this should be a given as qidi sponsors orca, and is better than a black screen where the design should be.

**Comment by QIDITECH** [comment]
We will change the preview image format to png in the next version, please wait for the update in the next version.

**Comment by QidiPrinter** [comment]
> We will change the preview image format to png in the next version, please wait for the update in the next version.

slow basta, too slow

**Comment by mirko-kienle** [comment]
The latest version of Orca Slicer ([1.9.0](https://github.com/SoftFever/OrcaSlicer/releases/tag/v1.9.0)) now automatically embeds preview images in the correct format, no need to wait for the firmware update. 🎉
