### ISSUE TITLE
Unload filament

### ISSUE THREAD

**Issue by rednet1** [QIDITECH/QIDI_SMART3#12]
I installed 4.1.12 on x-smart 3, filament unload doesn't work.

regards

**Comment by FestivaMan** [comment]
Did the UI update to 4.1.12 as well?

**Comment by rednet1** [comment]
I tried the update again but only the SOC is at version 4.1.12, UI still 4.1.10 (mcu 0.10.0)
I did a reset but it doesn't change.

regards

**Comment by FestivaMan** [comment]
Ok that's what was happening on both of mine as well. I ended up haveing to manually update the screen with an SD card.  Email the x-smart 3 support email that's on your printer and they will help you out with the file and instructions on how to do it.

**Comment by rednet1** [comment]
Support gave me a file I think for the screen, but the simple update procedure doesn't work, I turn it off, wait 30 seconds, log in but it doesn't update, in the USB there is only the file they sent me.

**Comment by FestivaMan** [comment]
Did you only try it with the USB port on the side of the machine?   Was the file something like MKSrecovery?  If so they my need to send you another file specifically for the screen, and there is a small SD card slot on the screen itself that I had to use to update my screen

**Comment by rednet1** [comment]
Solved, 

I disassembled the display :)
Thank

**Comment by FestivaMan** [comment]
Awesome.  Hope they can fix it for next time when it updates again.

**Comment by michalvankodev** [comment]
This seems to be still an issue with the 4.1.13 version I have just put on my xsmart3. I'm sorry, but I don't have an idea how to resolve this issue from your conversation.

**Comment by rednet1** [comment]
I also switched to version 4.1.13 which I just installed on my xsmart3 and I still had to disassemble the display.

**Comment by weidi** [comment]
Same for me..., waiting for the email. 
@QIDITECH  wouldn´t it be great to document the procedure and files needed publicly ?
