### ISSUE TITLE
BED_MESH_CALIBRATE & SHAPER_CALIBRATE FROM KLIPPER

### ISSUE THREAD

**Issue by rednet1** [QIDITECH/QIDI_SMART3#15]
I used the BED_MESH_CALIBRATE macro remotely but the plate did not stop blocking the printer, as if the probe did not read the plate, risk of breaking the printer, same thing with the SHAPER_CALIBRATE macro the plate rises and does not stop blocking the printer, it could seems very dangerous

**Comment by QIDITECH** [comment]
Before sending these two codes, we need to send G28 to make XYZ axis zero. Have you already sent G28?

**Comment by rednet1** [comment]
yes, I added the command to the macro, much better :)
