### ISSUE TITLE
Use a standard thumbnail type

### ISSUE THREAD

**Issue by andrewcharnley** [QIDITECH/QIDI_SMART3#16]
Currently qidislicer (based on prusaslicer) uses a custom thumbnail type. 

Change to using a standard format (jpg, png, gif, bmp) so that all slicers can generate thumbnails.

**Comment by QIDITECH** [comment]
X-smart 3 will no longer work with thumbnails in other formats because they load slowly.
And OrcaSlicer 1.9.0 already supports generating ColPic thumbnails.

**Comment by andrewcharnley** [comment]
Thank you I couldn't find information regarding the format.
