### ISSUE TITLE
Disable bed levelling option auto-tick on print start.

### ISSUE THREAD

**Issue by andrewcharnley** [QIDITECH/QIDI_SMART3#17]
The print start screen has a bed levelling checkbox which is always ticked on every print. The bed level doesn't change that often! This is an annoying 'feature'. Please think of someway to disable with retention - or simply have it unchecked by default.

**Comment by QIDITECH** [comment]
You can turn this off by commenting G29 in the start code.
![image](https://github.com/QIDITECH/QIDI_SMART3/assets/37525539/df9806db-0be7-462d-81d7-0aa94eac542e)

**Comment by andrewcharnley** [comment]
So with the checkbox unticked it calls a different macro?

**Comment by cl4nspi** [comment]
> So with the checkbox unticked it calls a different macro?

The macro behind G29 is skipped if the checkbox is unchecked.
