### ISSUE TITLE
movement beyond range of provision when auto leveling

### ISSUE THREAD

**Issue by minus1ms** [QIDITECH/QIDI_SMART3#2]
im getting "movement beyond range of provision" error when auto leveling, when printer is starting to collect 16 compensation points

**Comment by minus1ms** [comment]
i guess that its something related to values in config too, im curious, is there like different variant of this printer? like why default values are wrong for my printer?

**Comment by Rainboooom** [comment]
After the first batch of smart models were sold, we learned some issues from user feedback. We have made improvements to the hardware part of the machine. I remember I have already provided you with the contact information of the after-sales team before. You can inquire about relevant matters with them, and they will send you the new hardware facilities.

**Comment by minus1ms** [comment]
alright, thx

**Comment by JojoDevel** [comment]
I am having similar issues with the firmware version 4.1.2 and contacted the support team
