### ISSUE TITLE
Make UI work better

### ISSUE THREAD

**Issue by minus1ms** [QIDITECH/QIDI_SMART3#27]
Currently when u click a button, it detects when press started and not where it ended. If you accidentally touch some button but move your finger outside of it while holding and then release finger, it will still click this button. This behavior is not very good and its not hard to fix. UI should detect where finger was released and then do the action (so it should only work when same button was pressed and released). Another thing is that when you click a button and some action happens after that, you see only freezed screen till this action ends. This make the UI feel slightly unresponsive. After click, UI should display something like "Working..." or "Loading..." or inform about exact thing that is happening and after this thing ends it should continue what it was supposed to do (maybe stay in same page or go to another).

**Comment by CChen616** [comment]
Your feedback and suggestions are greatly appreciated. However, due to the limitations of the serial port screen used in this generation of printers, implementation is challenging. We will consider incorporating your suggestions into the next generation of printers.

**Comment by minus1ms** [comment]
thx
