### ISSUE TITLE
Problem with updates

### ISSUE THREAD

**Issue by luismrborges** [QIDITECH/QIDI_SMART3#28]
After the updates, the SoC version is updated, but the UI remains the same. Even after repeating the process, it doesn't update. This is a recurring problem with some updates. In this particular update (version 4.1.13), I encounter an issue where I am unable to reset to factory settings in the UI probably by being different versions.

**Comment by CChen616** [comment]
The SoC has been updated, please try to download and update again. 

Regarding factory reset, we only restored some of the printer configurations, so it may not work as you expected.
