### ISSUE TITLE
Pinout for Motherboard

### ISSUE THREAD

**Issue by RS-3D** [QIDITECH/QIDI_SMART3#31]
Hello,I need the pinout for the motherboard please. Can you provide me with the pinout?

Thanks

**Comment by Bixelec** [comment]
Hi, 

links to pinout image :
https://github.com/fran6p/Qidi_X-Max3/blob/main/Images/Qidi-mks-skipr-pins.png
https://github.com/fran6p/Qidi_X-Max3/blob/main/Images/qidi-skipr-pins.jpg

**Comment by RS-3D** [comment]
@Bixelec Thanks you very much. 😉
