### ISSUE TITLE
Smart 3 insert files wont update

### ISSUE THREAD

**Issue by chainsawsquirrel** [QIDITECH/QIDI_SMART3#8]
Loaded 4.1.12 files onto usb, inserted in machine.. machine not seeing any updates, reboted and tried again.. still nothing

**Comment by insp1re1** [comment]
works fine here. must be doing it wrong, fat32 usb?

**Comment by chainsawsquirrel** [comment]
Its the same usb stick I used for my xplus3 .. just deleted the plus3 files and dropped in the smart 3 files

**Comment by chainsawsquirrel** [comment]
No confusion .. the smart 3 gave me a white screen when done.. had to get file from support to fix that took 16 tries for that fix to work, tried another usb stick formatting it .. still nothing

**Comment by QIDITECH** [comment]
Please contact the after-sales service to confirm whether the printer hardware is damaged.
